spring.application.name=StudentManagement
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database URL
#spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
#
## DB credentials
#spring.datasource.username=postgres
#spring.datasource.password=1234